#!/usr/bin/env bash
# sync-cursor-rules.sh — derive a .cursor/rules/*.mdc file from the canonical
# scientific-method docs and the project's current PROTOCOL-HEADER.
#
# This is the confirmed-safe delivery path for Cursor: project rules under
# .cursor/rules/*.mdc are read automatically when the file has YAML
# frontmatter with alwaysApply: true (a plain .md with no frontmatter is
# ignored — same "trigger: always_on or it's Layer 1" gotcha already found
# for Devin's Windsurf rules in ../../devin/README.md). Unlike Cursor's
# sessionStart hook (see ../hooks/session-start-protocol.sh), this has no
# open upstream bug reports of silently not being read.
#
# Idempotent: only writes when content actually changed, same as
# ../../claude/hooks/sync-windsurf-rules.sh, which this is adapted from.
set -euo pipefail

usage() { echo "usage: sync-cursor-rules.sh PROJECT_DIR" >&2; exit 2; }
[ $# -eq 1 ] || usage
PROJECT_DIR="$(cd "$1" && pwd)"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
METHOD_DIR="$(cd "$HERE/../../method" && pwd)"
PROTOCOL="$PROJECT_DIR/SCIENTIFIC_PROTOCOL.md"
RULE_FILE="$PROJECT_DIR/.cursor/rules/scientific-method.mdc"
HEADER_SCRIPT="$METHOD_DIR/protocol-header.sh"

mkdir -p "$(dirname "$RULE_FILE")"

PROTOCOL_HEADER="(no SCIENTIFIC_PROTOCOL.md in this project — copy method/PROJECT_PROTOCOL_TEMPLATE.md first)"
if [ -f "$PROTOCOL" ]; then
  "$HEADER_SCRIPT" sync "$PROTOCOL" >/dev/null 2>&1 || true
  PROTOCOL_HEADER="$("$HEADER_SCRIPT" emit "$PROTOCOL" 2>/dev/null || echo "(header unavailable; read SCIENTIFIC_PROTOCOL.md directly)")"
fi

TMP="$(mktemp)"
{
  echo "---"
  echo "description: Scientific method — mandatory validation phases and protocol state"
  echo "alwaysApply: true"
  echo "---"
  echo ""
  echo "# $(basename "$PROJECT_DIR") — Scientific Method Enforcement"
  echo ""
  echo "Auto-generated by sync-cursor-rules.sh from the canonical method docs and"
  echo "this project's SCIENTIFIC_PROTOCOL.md. Do not edit by hand — edit the"
  echo "source and re-run the script."
  echo ""
  echo "## Mandatory first action of every session"
  echo ""
  echo "1. Read \`SCIENTIFIC_PROTOCOL.md\` with the read tool — source of truth"
  echo "   for phase, status, hypotheses, results, and incidents."
  echo "2. State the current phase and status before any other action."
  echo ""
  echo "Current protocol header (authoritative snapshot, not the full history):"
  echo ""
  printf '%s\n' "$PROTOCOL_HEADER"
  echo ""
  echo "## The method"
  echo ""
  sed -n '/^### 1\. State a falsifiable hypothesis/,/^## Anti-patterns/p' "$METHOD_DIR/SCIENTIFIC_METHOD.md" | sed '$d'
  echo "## Anti-patterns"
  echo ""
  sed -n '/^## Anti-patterns/,/^## What this does not cover/p' "$METHOD_DIR/SCIENTIFIC_METHOD.md" | sed '1d;$d'
} > "$TMP"

if [ -f "$RULE_FILE" ] && cmp -s "$RULE_FILE" "$TMP"; then
  echo "UNCHANGED: $RULE_FILE"
  rm -f "$TMP"
else
  mv "$TMP" "$RULE_FILE"
  echo "UPDATED: $RULE_FILE"
fi
